import { useEffect, useState } from 'react';
import AdminLayout from '@/components/AdminLayout';
import { CheckCircle2, Compass, Loader2, RefreshCw, Save } from 'lucide-react';

interface Builder { id:string; name:string; category:string; description:string; icon:string; status:string; plan_inclusion:string; token_cost:number; estimated_minutes:number; featured:number; visibility:string; builder_type:string; form_schema:string }

export default function AdminBuildersPage() {
  const [builders,setBuilders]=useState<Builder[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(''); const [notice,setNotice]=useState(''); const [error,setError]=useState('');
  const load=()=>{setLoading(true);setError('');fetch('/admin/api?section=builders',{credentials:'include'}).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.error||'Builders could not be loaded.');setBuilders(body.platform?.builders||[])}).catch(e=>setError(e.message)).finally(()=>setLoading(false))};
  useEffect(load,[]);
  const update=(id:string,patch:Partial<Builder>)=>setBuilders(current=>current.map(builder=>builder.id===id?{...builder,...patch}:builder));
  const save=async(builder:Builder)=>{setSaving(builder.id);setError('');setNotice('');try{const response=await fetch('/admin/api?section=builders',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(builder)});const body=await response.json();if(!response.ok)throw new Error(body.error||'Builder could not be saved.');setBuilders(body.platform?.builders||builders);setNotice(`${builder.name} saved.`)}catch(e:any){setError(e.message)}finally{setSaving('')}};
  return <AdminLayout title="Experience Builders" subtitle="Manage the guided planners available in JA Plan Studio."><div className="p-6 lg:p-8 space-y-6">
    <section className="rounded-3xl border border-blue-100 bg-gradient-to-br from-blue-50 to-white p-7 flex flex-col sm:flex-row sm:items-center justify-between gap-5"><div><p className="text-sm font-semibold text-blue-700 flex items-center gap-2"><Compass className="w-4 h-4"/>Experience planning only</p><h1 className="text-2xl font-bold text-slate-950 mt-2">Builder catalogue</h1><p className="text-slate-600 mt-2">Days out, occasions, trips and accessible experiences. Document, legal, policy, letter and report builders are not part of this catalogue.</p></div><button onClick={load} className="rounded-xl border border-slate-300 bg-white px-4 py-2.5 font-semibold flex items-center gap-2"><RefreshCw className="w-4 h-4"/>Refresh</button></section>
    {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}{notice&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-700 flex items-center gap-2"><CheckCircle2 className="w-4 h-4"/>{notice}</div>}
    {loading?<div className="py-20 flex justify-center"><Loader2 className="w-7 h-7 animate-spin text-blue-600"/></div>:<div className="grid xl:grid-cols-2 gap-5">{builders.map(builder=><article key={builder.id} className="rounded-2xl border border-slate-200 bg-white p-6 space-y-4"><div className="flex items-start gap-4"><div className="w-12 h-12 rounded-xl bg-blue-50 flex items-center justify-center text-2xl">{builder.icon||'✨'}</div><div className="flex-1"><input value={builder.name} onChange={e=>update(builder.id,{name:e.target.value})} className="w-full text-lg font-bold border-0 p-0 focus:ring-0"/><p className="text-xs text-slate-500 mt-1">{builder.id}</p></div><select value={builder.status} onChange={e=>update(builder.id,{status:e.target.value})} className="rounded-lg border border-slate-300 px-2 py-1.5 text-sm"><option>Active</option><option>Paused</option></select></div><textarea value={builder.description||''} onChange={e=>update(builder.id,{description:e.target.value})} rows={2} className="w-full rounded-xl border border-slate-300 px-3 py-2 text-sm"/><div className="grid sm:grid-cols-3 gap-3"><label className="text-xs text-slate-500">Category<input value={builder.category} onChange={e=>update(builder.id,{category:e.target.value})} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-900"/></label><label className="text-xs text-slate-500">Minutes<input type="number" value={builder.estimated_minutes||10} onChange={e=>update(builder.id,{estimated_minutes:Number(e.target.value)})} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-900"/></label><label className="text-xs text-slate-500">Trial<select value={builder.visibility} onChange={e=>update(builder.id,{visibility:e.target.value})} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-900"><option value="trial">Included</option><option value="paid">Paid only</option></select></label></div><div className="flex justify-end"><button onClick={()=>save(builder)} disabled={saving===builder.id} className="rounded-xl bg-blue-600 hover:bg-blue-700 text-white px-4 py-2.5 font-semibold flex items-center gap-2">{saving===builder.id?<Loader2 className="w-4 h-4 animate-spin"/>:<Save className="w-4 h-4"/>}Save builder</button></div></article>)}</div>}
  </div></AdminLayout>;
}
